### PR TITLE
adjust figures according to the template

### PR DESCRIPTION
**Pull request by zhxianlucky**
Hi Yanjie, I have adjusted the figures according to the template. Please see if the figures need to be resized.

### CODE REVIEW

**Review by YanjieGao — DISMISSED** [review]

**Comment by YanjieGao** [comment]
Hi Xian, the readme outline link of chapter 12 seems broken. Please help to fix.

https://github.com/microsoft/AI-System/tree/main/Textbook

**Comment by zhxianlucky** [comment]
> Hi Xian, the readme outline link of chapter 12 seems broken. Please help to fix.
> 
> https://github.com/microsoft/AI-System/tree/main/Textbook

Hi Yanjie, I have updated the table of contents and hyperlink in the README.

**Comment by YanjieGao** [comment]
https://github.com/microsoft/AI-System/pull/133 fix here

**Comment by YanjieGao** [comment]
Please resolve conflict

**Review by YanjieGao — APPROVED** [review]

**Pull request merged**
