### PR TITLE
fix bugs of Lecture 1 and 11

### PR DESCRIPTION
**Pull request by TobeyQin**
1. Fix typo on Lecture 1
2. Add more materials of Lecture 11
2. Remove temporary pages.

### CODE REVIEW

**Comment by YanjieGao** [comment]
Add () at

**Comment by YanjieGao** [comment]
intent mismatch

**Comment by YanjieGao** [comment]
Uppercase letter
image

**Comment by YanjieGao** [comment]
make consistent period
image

**Comment by YanjieGao** [comment]
Uppercase letter is better
image

**Comment by YanjieGao** [comment]
add a reference link from sklearn is better
image

**Comment by YanjieGao** [comment]
this break line is ugly, maybe not break line is better
image

**Comment by TobeyQin** [comment]
Resolved the problems. Thanks.

**Review by YanjieGao — APPROVED** [review]

**Pull request merged**
